# Generated by Django 3.2.8 on 2021-11-16 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20211116_2119'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.PositiveIntegerField(default=0, null=True, verbose_name='Количество товара'),
        ),
    ]
