# Generated by Django 3.2.8 on 2021-11-16 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_product_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default='help', upload_to='', verbose_name='Изображение'),
        ),
    ]
