# Generated by Django 3.1.1 on 2021-12-07 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20211207_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='orders',
            field=models.ManyToManyField(null=True, related_name='related_customer', to='main.Order', verbose_name='Заказы покупателя'),
        ),
    ]
